services:
  db:
    image: postgres:16
    container_name: mori-postgres
    restart: unless-stopped
    ports:
      - "${DB_PORT:-5434}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME:-mori}
      POSTGRES_USER: ${DB_USER:-raymond}
      POSTGRES_PASSWORD: ${DB_PASS:-mori1234}
      TZ: Asia/Seoul
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-raymond} -d ${DB_NAME:-mori}"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mori-app:local
    container_name: mori-app
    depends_on:
      db:
        condition: service_healthy        # DB healthy 후 기동
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: db            # 컨테이너 간 DNS 이름
      DB_PORT: "5432"
      DB_NAME: "${DB_NAME:-mori}"
      DB_USER: "${DB_USER:-raymond}"
      DB_PASS: "${DB_PASS:-mori1234}"

volumes:
  pgdata:
