spring:
  web:
    resources:
      add-mappings: true
  profiles:
    default: dev
    mvc:
      throw-exception-if-no-handler-found: true   # 404를 예외로 던짐
    web:
      resources:
        add-mappings: false                       # 정적 매핑 비활성화(전역 예외 처리로 일원화)
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: info
    org.hibernate.SQL: warn

management:
  server.port: 8081
  endpoints:
    web:
      exposure:
        include: [health, info]
  endpoint:
    health:
      show-details: when_authorized
