spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: info
    org.hibernate.SQL: warn

management:
  server.port: 8081
  endpoints:
    web:
      exposure:
        include: [health, info]
  endpoint:
    health:
      show-details: when_authorized
